server:
  port: 8081

spring:
  application:
    name: ms-categorias

  datasource:
    url: jdbc:mysql://localhost:3307/categorias_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /doc/swagger-ui.html

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  logging:
    level:
      root: INFO
      com.ms.categorias: DEBUG