server:
  port: 8085

spring:
  application:
    name: ms-auth

jwt:
  secret: miclaveultrasecretaparajwt
  expiration: 3600000

logging:
  level:
    root: INFO

usuarios:
  url: http://localhost:8084