server:
  port: 8085

spring:
  application:
    name: ms-auth

logging:
  level:
    root: INFO
    com.almacen.msauth: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

jwt:
  secret: miclave_super_secreta_2026
  expiration: 3600000